### ISSUE TITLE
Opencart 3

### ISSUE THREAD

**Issue by ricardotech88** [ifthenpay/opencart#7]
No opencart 3, os eventos associados ao getOrders 
checkMultibancoOrder
checkMbwayOrder

Estão a tornar incrivelmente lenta a listagem das vendas.
Estes eventos têm obrigatoriedade de estar activos?
Tendo os callback activos e testados, podemos desativar os eventos?

obrigado

**Comment by josesoaresif** [comment]
Sim podem desativar.
